dataset:
  train_path: "data/SQuAD-PL/train.csv"
  test_path: "data/SQuAD-PL/test.csv"
  back_translate_paths:
  - "data/SQuAD-PL/train_pl_it_pl.csv"
  - "data/SQuAD-PL/train_pl_vi_sv_pl.csv"
  sample_size: 500
  dev_size: 0.2
model:
  path: "models/herbert-base-cased"
  max_length: 384
  stride: 128
train:
  seed: 42
  epochs: 2
  batch_size: 4
  gradient_accumulation: 4
  weight_decay: 1.0e-2
  lr_initial: 1.0e-5
  lr_peak: 1.0e-5
  lr_final: 1.0e-5
  t_warmup: 1
  t_decay: 1
  save_path: "experiments/squad-10k-herbert-all"
  save_best: true
  save_checkpoint: false
  save_each_epoch: false
augmentation:
  enabled: true
  p_back_translate: 0.5
  p_replace_question: 0.3
  p_replace_question_entity: 0.3
  p_drop_answer: 0.01
  p_drop_token: 0.01
  p_drop_char: 0.01
  p_replace_polish_char: 0.1
